version: '2'
services:
    sakura-app:
        image: sakura
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sakura-postgresql:5432/sakura
            - JHIPSTER_CACHE_MEMCACHED_SERVERS=sakura-memcached:11211
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sakura-postgresql:
        extends:
            file: postgresql.yml
            service: sakura-postgresql
    sakura-memcached:
        extends:
            file: memcached.yml
            service: sakura-memcached
