version: '2'
services:
    sakura-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/sakura/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=sakura
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
